name: Check
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build_mocklinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build mocklinux
        working-directory: mocklinux
        run: make

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target folder
        uses: actions/cache@v5
        with:
          path: target
          key: cargo-target-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Lint with Clippy
        run: cargo clippy --all-features --all-targets

      - name: Check formatting
        run: cargo fmt --check

      - name: Build Debug
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Build Release
        run: cargo build --release
